api_platform:
    title: "Ndombi API"
    version: 1.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity','%kernel.project_dir%/public/bundles/apiplatform']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
